source 'https://github.com/CocoaPods/Specs.git' 

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CashFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CashFlow
  pod 'GoogleMLKit/TextRecognition', '3.2.0'

end
